### ISSUE TITLE
Heads up, next release will use the Roslyn compiler

### ISSUE THREAD

**Issue by fusion809** [diddlesnaps/openra#10]
Hi,

In case you're not aware, the next release of OpenRA will use a different compiler, requiring Mono 5.10 or later (preferably 5.12 or later) and MSBuild. I'm surprised this package has no additional channels, like a bleeding-edge channel providing builds from the latest commits, but I suppose they come out quite frequently, so it might not be feasible. Such a channel might be a helpful temporary measure, as a way to test build the later Roslyn-using commits. 

Hope this helps

**Comment by diddledan** [comment]
thanks. the snap is building fine with the new releases now.
