### ISSUE TITLE
Please add the newest playtest version

### ISSUE THREAD

**Issue by Recydywa** [diddlesnaps/openra#12]
When I check the version of the snap I get:

> channels:
  latest/stable:    20191117 2020-01-24 (183) 69MB -
  latest/candidate: ↑                              
  latest/beta:      ↑                              
  latest/edge:      20200202 2020-02-21 (207) 70MB -

Which is kind of wrong becasue 20200202 is the latest stable release of OpenRA. I think that under edge channel should be the latest Playtest version (currently 20200303).

So if it is possible please update the snap packages.

**Comment by diddledan** [comment]
I've been working hard behind the scenes to get this operational. The commit I added just now should get us a working automated build of playtests to edge and stable to beta. Check the snap store later today to find out if the build succeeded :-)

**Comment by Recydywa** [comment]
Thank you.

> $ snap info openra
name:    openra
summary: A Libre/Free Real Time Strategy game engine supporting early
  Westwood classics
...
tracking:     latest/stable
refresh-date: 12 days ago, at 23:44 CEST
channels:
  latest/stable:    release-20200503  2020-05-03  (236) 220MB -
  latest/candidate: ↑                                         
  latest/beta:      release-20200503  2020-05-14 (1270) 220MB -
  **latest/edge:      playtest-20200426** 2020-05-14 (1269) 220MB -
installed:          release-20200503              (236) 220MB -
