### ISSUE TITLE
No network

### ISSUE THREAD

**Issue by kurthuwig** [diddlesnaps/openra#15]
Both the Internet download of the game data as well as connecting to another server do not work.

The game data download reports "no DNS"

When I install the game data manually - which should be documented as well that you need to put it into

~/snap/openra/1327/.config/openra/

The lobby is empty.

Using "Direct IP" reports that it cannot connect to the local server in the same network.

How can I enable networking in the snap?

**Comment by diddledan** [comment]
This sounds like a host issue, not openra-specific. Please try other snaps to see if they also cannot access the network. Also check that non-snapped applications can access the network.  Also try rebooting your host. 

The output of `snap connections openra` might reveal issues with the snap interface connections which will indicate snapd has gone wonky.

**Comment by diddledan** [comment]
Is this still an issue? I'm closing the report for now, but please reopen if you're still having trouble.
