### ISSUE TITLE
release-20210321

### ISSUE THREAD

**Issue by delanym** [diddlesnaps/openra#16]
Pls add :D

**Comment by fsck-block** [comment]
I second that!

**Comment by diddledan** [comment]
Sorry about the delay, it seems I messed-up the store upload part of the automated builder. This should be fixed, and you should now be able to see the 20210321 release in the beta channel...

**Comment by delanym** [comment]
@diddledan now its broken

```
Exception of type `System.TypeLoadException`: Could not load type of field 'OpenRA.Network.UPnP:natDevice' (0) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
TypeName=`OpenRA.Network.UPnP`
  at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00006] in <301cf1e0dfb5443ab64bf1eb3f73b6ad>:0 
  at OpenRA.Launcher.Program.Main (System.String[] args) [0x00044] in <964349ffb59c4b6ca13908159ea1fda2>:0 

Red Alert has encountered a fatal error.
Please refer to the crash logs and FAQ for more information.

Log files are located in /home/sol/snap/openra/1341/.config/openra/Logs
The FAQ is available at http://wiki.openra.net/FAQ

```

**Comment by Franchute13** [comment]
> @diddledan now its broken
> 
> ```
> Exception of type `System.TypeLoadException`: Could not load type of field 'OpenRA.Network.UPnP:natDevice' (0) due to: Could not load file or assembly 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies.
> TypeName=`OpenRA.Network.UPnP`
>   at OpenRA.Game.InitializeAndRun (System.String[] args) [0x00006] in <301cf1e0dfb5443ab64bf1eb3f73b6ad>:0 
>   at OpenRA.Launcher.Program.Main (System.String[] args) [0x00044] in <964349ffb59c4b6ca13908159ea1fda2>:0 
> 
> Red Alert has encountered a fatal error.
> Please refer to the crash logs and FAQ for more information.
> 
> Log files are located in /home/sol/snap/openra/1341/.config/openra/Logs
> The FAQ is available at http://wiki.openra.net/FAQ
> ```

Same problem!

**Comment by pchote** [comment]
I don't have much experience with snap, but I took a quick look to see if i could offer any advice on how to proceed here.

Looking at the mono files we ship inside the OpenRA AppImage (`OpenRA-xxx.AppImage --appimage-mount`), the snap is missing `/snap/openra/current/usr/lib/mono/4.5/Facades/netstandard.dll`. This library was a problem for us too https://github.com/OpenRA/AppImageSupport/commit/2e1f7a062740f805c1cc0b848ed41155fc20e765... there is something weird about how the upstream mono packages dealt with this.

Fortunately this is going to be the last release where we need to worry about Mono problems - the next release will (so long as you don't override it back to Mono with a compile arg) use the .NET5 runtime, and automatically package the needed runtime files along with the game files through the `make install` target.

**Comment by Franchute13** [comment]
diddledan, new beta (20210321-release 18 april) work OK.
Thanks

**Comment by scips** [comment]
@Franchute13 could you fork and make a pull request with the 20210321 release of April 18?

**Comment by dethos** [comment]
In snapscraft's store the latest version is not yet available for the `arm64` architecture. The information provided is that it is still using `release-20200503`. Any plans for an update?
