### ISSUE TITLE
missing lib on arm64 (Ubuntu Desktop for RaspPi)

### ISSUE THREAD

**Issue by tomek113** [diddlesnaps/openra#17]
Snap install fails with below error message (I tried stable and edge version):

error: cannot perform the following tasks:
- Run install hook of "openra" snap if present (run hook "install": /snap/openra/1361/usr/bin/mono: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory)

**Comment by dethos** [comment]
I'm facing the same problem on a Raspberry Pi 4 (OS: Manjaro). The output in all channels is similar:

```
$ snap install openra
error: cannot perform the following tasks:
- Run install hook of "openra" snap if present (run hook "install": 
-----
WARNING: cgroup v2 is not fully supported yet, proceeding with partial confinement
/snap/openra/1361/usr/bin/mono: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```

**Comment by dethos** [comment]
@diddledani any idea about how could we solve this problem?

**Comment by diddledani** [comment]
unfortunately builds are failing at the moment - there seems to be a dotnet/mono+qemu-user compatibility issue.

**Comment by tomek113** [comment]
> @diddledani any idea about how could we solve this problem?

If this helps, I was able to build OpenRA-release-20210321 from source on Raspberry Pi 4B. You just need to use .NET 5 SDK instead of mono.

**Comment by diddledani** [comment]
Thanks, @tomek113, I'll have a poke at the build to see if I can fix it

**Comment by lucyllewy** [comment]
You can now install openra on an arm64 machine. I have finally managed to get the build system working correctly. The armhf build is still not working correctly, so you need to be using a 64bit version of linux on your pi.
