### ISSUE TITLE
[Enhancement]: Please update to new release

### ISSUE THREAD

**Issue by MartinMiller** [diddlesnaps/openra#23]
#### New release 20230225
There has been a new release since 25th of February 2023. Please update the snap to new release.

**Comment by Joesalmon1985** [comment]
How hard is it to update the snap? I've only ever really mucked about with a bit of python and work with SQL and just do the ubuntu thing as a hobby and love playing openra on my machine.

I thought it'd be as simple as updating this bit of code below and that I'd have a crack at getting chatGPT talk me through it, but I've not been able to make head or tale of it.

https://github.com/diddlesnaps/openra/blob/master/snap/snapcraft.yaml

**Comment by diddledani** [comment]
The latest stable and playlets builds for amd64 and arm64 (armhf build is still not completing properly in CI) should now be available in the beta and edge channels respectively - I haven't had a chance to verify the builds are operational once installed, however, so they may not function as expected - if you can verify the beta builds for either of amd64 or arm64 are working well then I can promote them to stable. Otherwise it will need to wait till sometime next week for me to verify their sanity when I'm back home.

**Comment by MartinMiller** [comment]
Thx diddledani. Just installed the beta channel. 
Had a problem with the server browser. Error message is: "You are running a unrecognized version of OpenRA. Download the latest version from www.openra.net". Needs to be fixed for stable.
Everything else seems fine.

**Comment by MartinMiller** [comment]
Update:
When I start the beta channel the output shows a wrong release string (see below). It shows "release-20230225^0" not "release-20230225". I think this will fix the server browser issue mentioned above.

Platform is Linux (X64)
Engine version is release-20230225^0
Runtime: .NET CLR 6.0.14
Using SDL 2 with OpenGL (Modern) renderer
Desktop resolution: 1920x1080
No custom resolution provided, using desktop resolution
Using resolution: 1920x1080
Using window scale 1,00
OpenGL renderer: Mesa Intel(R) UHD Graphics 620 (WHL GT2)
OpenGL version: 4.6 (Core Profile) Mesa 22.2.5
Using default sound device
Internal mods:
	cnc: Tiberian Dawn (release-20230225^0)
	d2k: Dune 2000 (release-20230225^0)
	modcontent: Mod Content Manager (release-20230225^0)
	ra: Red Alert (release-20230225^0)
	ts: Tiberian Sun (release-20230225^0)
External mods:
	ra-release-20230225^0: Red Alert (release-20230225^0)
Loading mod: ra

**Comment by diddledani** [comment]
Thanks for looking into it. I'll see if I can figure out the reason the version string has that extra `^0` at the end and get it to rebuild without it during this week.

**Comment by MartinMiller** [comment]
Beta channel seems fine now. For amd64 i think it can be promoted to stable. Thanks for you efforts diddledani.

**Comment by diddledani** [comment]
Thank you so much for verifying it for me :-) I'll promote amd64. I'm just about to check arm64. The build for armhf is broken due to a segfault with snapd/snapcraft unrelated to the opera build itself, but seems to be specific to running my containerised build mechanism on Oracle Cloud's A1 VMs.

**Comment by diddledani** [comment]
ok, a quick smoke test of arm64 seems to be fine <3 I'll promote both to stable now :-) Thank you so much for your help!
